-- 1. Create profiles table
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  name text,
  dob date,
  gender text,
  address text,
  blood_group text,
  contact text,
  emergency_contact_name text,
  emergency_contact text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create allergies table
create table public.allergies (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  severity text default 'mild'::text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create medicines table
create table public.medicines (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  dosage text,
  frequency text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create surgeries table
create table public.surgeries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  surgery_date date,
  hospital text,
  surgeon text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.allergies enable row level security;
alter table public.medicines enable row level security;
alter table public.surgeries enable row level security;

-- 6. Setup RLS Policies (Allows doctors/public to read records, and users to manage their own data)
-- Profiles policies
create policy "Allow public read access to profiles for emergency" on public.profiles for select using (true);
create policy "Allow users to insert their own profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Allow users to update their own profile" on public.profiles for update using (auth.uid() = id);

-- Allergies policies
create policy "Allow public read access to allergies for emergency" on public.allergies for select using (true);
create policy "Allow users to manage their own allergies" on public.allergies for all using (auth.uid() = user_id);

-- Medicines policies
create policy "Allow public read access to medicines for emergency" on public.medicines for select using (true);
create policy "Allow users to manage their own medicines" on public.medicines for all using (auth.uid() = user_id);

-- Surgeries policies
create policy "Allow public read access to surgeries for emergency" on public.surgeries for select using (true);
create policy "Allow users to manage their own surgeries" on public.surgeries for all using (auth.uid() = user_id);
